services:
  - type: web
    # give it a distinct name so you don’t collide with your English service
    name: health-analysis-zh
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    # point at your zh‐module and bind to the Render $PORT
    startCommand: gunicorn health_analysis_zh:app --bind 0.0.0.0:$PORT

    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: SMTP_PASSWORD
        value: ${SMTP_PASSWORD}
